import { Submission, Status, RefcekData, RefcekProgress, KandidatStatus, LaporanData, WomData, WomJatengRefcekData } from './types';

export const DUMMY_SUBMISSIONS: Submission[] = [
  {
    id: 'd1',
    submissionDate: new Date(new Date().setDate(new Date().getDate() - 2)).toISOString(),
    namaLengkap: 'Budi Santoso',
    jenisKelamin: 'Laki-laki',
    ttl: 'Jakarta, 10 Januari 1995',
    nomorKTP: '3171234567890001',
    alamatKTP: 'Jl. Merdeka No. 1, Jakarta Pusat',
    alamatDomisili: 'Jl. Merdeka No. 1, Jakarta Pusat',
    nomorHP: '081234567890',
    agama: 'Islam',
    namaIbu: 'Siti Aminah',
    ttlIbu: 'Bandung, 5 Mei 1970',
    pengalamanKerja: 'PT. Maju Mundur - Staff Marketing',
    masaKerja: '1 Januari 2020 – 31 Desember 2022',
    namaAtasan: 'Rahmat Hidayat – Manager',
    nomorAtasan: '081209876543',
    alasanResign: 'Mencari tantangan baru',
    facebook: 'budisantoso.official',
    instagram: 'budisans',
    linkedin: 'budi-santoso',
    email: 'budi.santoso@example.com',
    golonganDarah: 'O',
    status: Status.ON_PROSES,
  },
  {
    id: 'd2',
    submissionDate: new Date().toISOString(),
    namaLengkap: 'Citra Lestari',
    jenisKelamin: 'Perempuan',
    ttl: 'Surabaya, 22 Maret 1998',
    nomorKTP: '3578123456780002',
    alamatKTP: 'Jl. Pahlawan No. 10, Surabaya',
    alamatDomisili: 'Apartemen Sejahtera Tower B, Surabaya',
    nomorHP: '085678901234',
    agama: 'Kristen',
    namaIbu: 'Maria Dewi',
    ttlIbu: 'Surabaya, 11 November 1972',
    pengalamanKerja: 'CV. Cipta Karya – Admin',
    masaKerja: '1 Juni 2021 – 30 Mei 2023',
    namaAtasan: 'Andi Wijaya – Supervisor',
    nomorAtasan: '085611223344',
    alasanResign: 'Pindah domisili',
    facebook: 'citra.lestari.98',
    instagram: 'citralestar',
    linkedin: 'citra-lestari',
    email: 'citra.lestari@example.com',
    golonganDarah: 'A',
    status: Status.PENDING,
  }
];


export const DUMMY_REFCEK_DATA: RefcekData[] = [
  {
    id: 'rc1',
    tanggalEmailRequest: '2023-10-26',
    jamEmailRequestMasuk: '09:15',
    checker1: 'Andi',
    tanggalDikirim: '2023-10-26',
    jamHasilDikirim: '14:30',
    progressReffcheck: RefcekProgress.SELESAI,
    checker2: 'Sari',
    checker3: 'Rina',
    statusKandidat: KandidatStatus.REKOMENDASI,
    perusahaan: 'PT. Teknologi Maju',
    cabang: 'Jakarta Pusat',
    posisiPekerjaan: 'Software Engineer',
    namaLengkap: 'Dewi Anggraini',
    nomorTlpAtauWA: '081234567891',
    kendalaUpdate: '-',
    kendalaReport: '-',
    keterangan: 'Kandidat memiliki rekam jejak yang sangat baik.',
    buArea: 'John Doe',
  },
  {
    id: 'rc2',
    tanggalEmailRequest: '2023-10-27',
    jamEmailRequestMasuk: '11:00',
    checker1: 'Budi',
    tanggalDikirim: '',
    jamHasilDikirim: '',
    progressReffcheck: RefcekProgress.PROSES_CHECKER_2,
    checker2: 'Sari',
    checker3: '',
    statusKandidat: KandidatStatus.PERTIMBANGAN_USER,
    perusahaan: 'CV. Kreatif Solusi',
    cabang: 'Bandung',
    posisiPekerjaan: 'Graphic Designer',
    namaLengkap: 'Eko Prasetyo',
    nomorTlpAtauWA: '081234567892',
    kendalaUpdate: 'Atasan sebelumnya sulit dihubungi.',
    kendalaReport: 'Atasan sebelumnya sulit dihubungi.',
    keterangan: 'Menunggu konfirmasi dari referensi kedua.',
    buArea: 'Jane Smith',
  }
];

export const DUMMY_LAPORAN_DATA: LaporanData[] = [
  {
    id: 'lap1',
    tanggalRequest: '2024-05-20',
    perusahaan: 'PT. Sejahtera Abadi',
    cabang: 'Jakarta Selatan',
    posisiPekerjaan: 'Account Officer',
    statusKandidat: 'Selesai',
    tanggaTerbit: '2024-05-22',
    sumberKandidat: 'Job Portal',
    namaLengkap: 'Andi Wijaya',
    jenisKelamin: 'Laki-laki',
    tempatTglLahir: 'Bekasi, 12 Juni 1996',
    nomorKTP: '3275123456780001',
    alamatDomisili: 'Jl. Mawar No. 5, Bekasi',
    alamatKTP: 'Jl. Mawar No. 5, Bekasi',
    noHpWa: '081298765432',
    agama: 'Islam',
    namaIbuKandung: 'Rina Marlina',
    tempatTglLahirIbuKandung: 'Cirebon, 1 Januari 1975',
    bidangUsaha: 'Financing',
    pengalamanPekerjaan: 'PT. Makmur Jaya - Marketing',
    masaKerjaKandidat: '2 tahun',
    referensi: 'Bapak Subagio - Manager',
    nomorTeleponReferensi: '081122334455',
    alasanResign: 'Mencari peluang karir yang lebih baik',
    akunSosialMedia: 'IG: @andiwijaya',
    email: 'andi.wijaya@example.com',
    golDarah: 'A',
    masalahKehadiran: 'Tidak ada',
    relasiDenganAtasan: 'Baik',
    terkaitIntegritas: 'Tidak ada catatan negatif',
    performance: 'Memenuhi target secara konsisten',
    penjelasanResign: 'Ingin berkembang di perusahaan yang lebih besar.',
    hasilRekomendasi: 'Direkomendasikan',
    justifikasi: 'Kandidat memiliki pengalaman yang relevan dan rekam jejak yang baik.',
    keterangan: 'Proses verifikasi berjalan lancar.',
  },
];

export const DUMMY_WOM_DATA: WomData[] = [
  {
    id: 'wom1',
    tanggalReffCheck: '2024-07-28',
    namaPelamar: 'Rina Hartati',
    cabang: 'Surabaya',
    lokasiKerja: 'Surabaya',
    bu: 'Jawa Timur',
    source: 'Walk-in',
    jenisKelamin: 'P',
    tempatLahir: 'Gresik',
    tanggalLahir: '1997-08-19',
    nomorKtp: '3578012345670003',
    agama: 'Islam',
    alamatKtp: 'Jl. Kenjeran No. 20, Surabaya',
    noTelp: '081333444555',
    namaIbuKandung: 'Sri Wahyuni',
    tempatLahirIbu: 'Lamongan',
    tanggalLahirIbu: '1975-02-15',
    statusKandidat: 'Rekomendasi',
    posisiDilamar: 'Customer Service',
    pengalaman: '2 Tahun di Bank Swasta',
    namaPerusahaan: 'Bank Sentosa',
    bidangUsaha: 'Perbankan',
    pemberiReferensi: 'Bapak Hartono',
    nomorTeleponReferensi: '081222333444',
    jabatanReferensi: 'Branch Manager',
    jabatanTerakhirKandidat: 'Senior Customer Service',
    masaKerjaKandidat: '2022-2024',
    masalahKehadiran: 'Tidak ada',
    tidakMasukTanpaIzin: 'Tidak pernah',
    masalahKesehatan: 'Tidak ada',
    relasiDengan: 'Sangat baik dengan rekan kerja dan atasan',
    terkaitIntegritas: 'Sangat jujur dan dapat dipercaya',
    performance: 'Selalu melebihi target kepuasan pelanggan',
    alasanResign: 'Ingin mencari jenjang karir yang lebih tinggi',
    penjelasanResign: 'Perusahaan sebelumnya tidak menawarkan promosi internal.',
    facebook: 'rina.hartati.real',
    instagram: 'rhartati',
    twitter: '',
    akunMediaSosialLainnya: 'LinkedIn: rina-hartati',
    kelebihanKandidat: 'Komunikatif, sabar, dan problem solver yang baik.',
    kekuranganKandidat: 'Terkadang terlalu perfeksionis.',
    email: 'rina.hartati@example.com',
    golonganDarah: 'B',
    rekomendasi: 'Sangat Direkomendasikan',
    justifikasi: 'Kandidat menunjukkan kompetensi dan etos kerja yang tinggi.'
  }
];

export const DUMMY_WOM_JATENG_REFCEK_DATA: WomJatengRefcekData[] = [
  {
    id: 'wjr1',
    createdAt: new Date().toISOString(),
    namaKandidat: 'FIRYAL SALSABILA',
    posisiDilamar: 'MAO MOTOR',
    cabangKapos: 'KAJEN',
    statusKandidat: 'New Hire Eksternal',
    pengalaman: ['Fresh graduated, pengalaman freelance'],
    namaPerusahaan: 'MEMBANTU IBU BERJUALAN KUE (AGUSTUS 2024 S.D SAAT INI)',
    pemberiReferensiNama: 'Ibu Kandidat',
    pemberiReferensiJabatan: 'Pemilik Usaha',
    pemberiReferensiTelp: '081234567890',
    masaKerjaTahun: '0',
    masaKerjaBulan: '1',
    masalahKehadiran: 'Tepat Waktu',
    tidakMasukIzin: '0',
    masalahKesehatan: 'Tidak Pernah Sakit yang Berkepanjangan',
    masalahKesehatanDetail: '',
    relasiAtasan: 'Baik',
    relasiAtasanDetail: '',
    relasiRekan: 'Baik',
    relasiRekanDetail: '',
    relasiBawahan: 'Baik',
    relasiBawahanDetail: '',
    integritas: 'Tidak ada masalah Fraud',
    integritasDetail: '',
    performance: 'On Target',
    alasanResignI: 'Mengundurkan Diri Baik-Baik',
    alasanResignII: [],
    alasanResignIII: '',
    alasanResignIVPenjelasan: 'Mencari pekerjaan tetap.',
    akunMedsosAlamat: 'CACAAFIR',
    akunMedsosStatus: ['Baik - Akun tidak mengandung hal negatif'],
    akunMedsosLainnya: '',
    rekomendasi: 'Direkomendasikan',
    justifikasi: 'Kandidat menunjukkan motivasi yang tinggi untuk belajar dan berkembang.',
    email: 'salsabilafir3@gmail.com',
  }
];