import { Submission, Status, RefcekData, RefcekProgress, KandidatStatus } from './types';

export const DUMMY_SUBMISSIONS: Submission[] = [
  {
    id: 'd1',
    submissionDate: new Date(new Date().setDate(new Date().getDate() - 2)).toISOString(),
    namaLengkap: 'Budi Santoso',
    jenisKelamin: 'Laki-laki',
    ttl: 'Jakarta, 10 Januari 1995',
    nomorKTP: '3171234567890001',
    alamatKTP: 'Jl. Merdeka No. 1, Jakarta Pusat',
    alamatDomisili: 'Jl. Merdeka No. 1, Jakarta Pusat',
    nomorHP: '081234567890',
    agama: 'Islam',
    namaIbu: 'Siti Aminah',
    ttlIbu: 'Bandung, 5 Mei 1970',
    pengalamanKerja: 'PT. Maju Mundur - Staff Marketing',
    masaKerja: '1 Januari 2020 – 31 Desember 2022',
    namaAtasan: 'Rahmat Hidayat – Manager',
    nomorAtasan: '081209876543',
    alasanResign: 'Mencari tantangan baru',
    facebook: 'budisantoso.official',
    instagram: 'budisans',
    linkedin: 'budi-santoso',
    email: 'budi.santoso@example.com',
    golonganDarah: 'O',
    status: Status.ON_PROSES,
  },
  {
    id: 'd2',
    submissionDate: new Date().toISOString(),
    namaLengkap: 'Citra Lestari',
    jenisKelamin: 'Perempuan',
    ttl: 'Surabaya, 22 Maret 1998',
    nomorKTP: '3578123456780002',
    alamatKTP: 'Jl. Pahlawan No. 10, Surabaya',
    alamatDomisili: 'Apartemen Sejahtera Tower B, Surabaya',
    nomorHP: '085678901234',
    agama: 'Kristen',
    namaIbu: 'Maria Dewi',
    ttlIbu: 'Surabaya, 11 November 1972',
    pengalamanKerja: 'CV. Cipta Karya – Admin',
    masaKerja: '1 Juni 2021 – 30 Mei 2023',
    namaAtasan: 'Andi Wijaya – Supervisor',
    nomorAtasan: '085611223344',
    alasanResign: 'Pindah domisili',
    facebook: 'citra.lestari.98',
    instagram: 'citralestar',
    linkedin: 'citra-lestari',
    email: 'citra.lestari@example.com',
    golonganDarah: 'A',
    status: Status.PENDING,
  }
];


export const DUMMY_REFCEK_DATA: RefcekData[] = [
  {
    id: 'rc1',
    tanggalEmailRequest: '2023-10-26',
    jamEmailRequestMasuk: '09:15',
    checker1: 'Andi',
    tanggalDikirim: '2023-10-26',
    jamHasilDikirim: '14:30',
    progressReffcheck: RefcekProgress.SELESAI,
    checker2: 'Sari',
    checker3: 'Rina',
    statusKandidat: KandidatStatus.REKOMENDASI,
    perusahaan: 'PT. Teknologi Maju',
    cabang: 'Jakarta Pusat',
    posisiPekerjaan: 'Software Engineer',
    namaLengkap: 'Dewi Anggraini',
    nomorTlpAtauWA: '081234567891',
    kendalaUpdate: '-',
    kendalaReport: '-',
    keterangan: 'Kandidat memiliki rekam jejak yang sangat baik.',
    buArea: 'John Doe',
  },
  {
    id: 'rc2',
    tanggalEmailRequest: '2023-10-27',
    jamEmailRequestMasuk: '11:00',
    checker1: 'Budi',
    tanggalDikirim: '',
    jamHasilDikirim: '',
    progressReffcheck: RefcekProgress.PROSES_CHECKER_2,
    checker2: 'Sari',
    checker3: '',
    statusKandidat: KandidatStatus.PERTIMBANGAN_USER,
    perusahaan: 'CV. Kreatif Solusi',
    cabang: 'Bandung',
    posisiPekerjaan: 'Graphic Designer',
    namaLengkap: 'Eko Prasetyo',
    nomorTlpAtauWA: '081234567892',
    kendalaUpdate: 'Atasan sebelumnya sulit dihubungi.',
    kendalaReport: 'Atasan sebelumnya sulit dihubungi.',
    keterangan: 'Menunggu konfirmasi dari referensi kedua.',
    buArea: 'Jane Smith',
  }
];