import { Submission, Status, RefcekData, RefcekProgress, KandidatStatus, LaporanData, WomData, WomJatengRefcekData, WomSulawesiRefcekData, MafRefcekData, McfRefcekData, AdiraRefcekData } from './types';
import {
  suciSignature,
  yeniSignature,
  wisnuSignature,
  annisaSignature,
  febrianaSignature,
  paramitaSignature,
  cahyaSignature,
  nurKholifahSignature,
  bimoSignature,
} from './assets/signatures';

export const DUMMY_SUBMISSIONS: Submission[] = [
  {
    id: 'd1',
    submissionDate: new Date(new Date().setDate(new Date().getDate() - 2)).toISOString(),
    namaLengkap: 'Budi Santoso',
    jenisKelamin: 'Laki-laki',
    ttl: 'Jakarta, 10 Januari 1995',
    nomorKTP: '3171234567890001',
    alamatKTP: 'Jl. Merdeka No. 1, Jakarta Pusat',
    alamatDomisili: 'Jl. Merdeka No. 1, Jakarta Pusat',
    nomorHP: '081234567890',
    agama: 'Islam',
    namaIbu: 'Siti Aminah',
    ttlIbu: 'Bandung, 5 Mei 1970',
    pengalamanKerja: 'PT. Maju Mundur - Staff Marketing',
    masaKerja: '1 Januari 2020 – 31 Desember 2022',
    namaAtasan: 'Rahmat Hidayat – Manager',
    nomorAtasan: '081209876543',
    alasanResign: 'Mencari tantangan baru',
    facebook: 'budisantoso.official',
    instagram: 'budisans',
    linkedin: 'budi-santoso',
    email: 'budi.santoso@example.com',
    golonganDarah: 'O',
    status: Status.ON_PROSES,
  },
  {
    id: 'd2',
    submissionDate: new Date().toISOString(),
    namaLengkap: 'Citra Lestari',
    jenisKelamin: 'Perempuan',
    ttl: 'Surabaya, 22 Maret 1998',
    nomorKTP: '3578123456780002',
    alamatKTP: 'Jl. Pahlawan No. 10, Surabaya',
    alamatDomisili: 'Apartemen Sejahtera Tower B, Surabaya',
    nomorHP: '085678901234',
    agama: 'Kristen',
    namaIbu: 'Maria Dewi',
    ttlIbu: 'Surabaya, 11 November 1972',
    pengalamanKerja: 'CV. Cipta Karya – Admin',
    masaKerja: '1 Juni 2021 – 30 Mei 2023',
    namaAtasan: 'Andi Wijaya – Supervisor',
    nomorAtasan: '085611223344',
    alasanResign: 'Pindah domisili',
    facebook: 'citra.lestari.98',
    instagram: 'citralestar',
    linkedin: 'citra-lestari',
    email: 'citra.lestari@example.com',
    golonganDarah: 'A',
    status: Status.PENDING,
  }
];


export const DUMMY_REFCEK_DATA: RefcekData[] = [
  {
    id: 'rc1',
    tanggalEmailRequest: '2023-10-26',
    jamEmailRequestMasuk: '09:15',
    checker1: 'Andi',
    tanggalDikirim: '2023-10-26',
    jamHasilDikirim: '14:30',
    progressReffcheck: RefcekProgress.SELESAI,
    checker2: 'Sari',
    checker3: 'Rina',
    statusKandidat: KandidatStatus.REKOMENDASI,
    perusahaan: 'PT. Teknologi Maju',
    cabang: 'Jakarta Pusat',
    posisiPekerjaan: 'Software Engineer',
    namaLengkap: 'Dewi Anggraini',
    nomorTlpAtauWA: '081234567891',
    kendalaUpdate: '-',
    kendalaReport: '-',
    keterangan: 'Kandidat memiliki rekam jejak yang sangat baik.',
    buArea: 'John Doe',
  },
  {
    id: 'rc2',
    tanggalEmailRequest: '2023-10-27',
    jamEmailRequestMasuk: '11:00',
    checker1: 'Budi',
    tanggalDikirim: '',
    jamHasilDikirim: '',
    progressReffcheck: RefcekProgress.PROSES_CHECKER_2,
    checker2: 'Sari',
    checker3: '',
    statusKandidat: KandidatStatus.PERTIMBANGAN_USER,
    perusahaan: 'CV. Kreatif Solusi',
    cabang: 'Bandung',
    posisiPekerjaan: 'Graphic Designer',
    namaLengkap: 'Eko Prasetyo',
    nomorTlpAtauWA: '081234567892',
    kendalaUpdate: 'Atasan sebelumnya sulit dihubungi.',
    kendalaReport: 'Atasan sebelumnya sulit dihubungi.',
    keterangan: 'Menunggu konfirmasi dari referensi kedua.',
    buArea: 'Jane Smith',
  }
];

export const DUMMY_LAPORAN_DATA: LaporanData[] = [
  {
    id: 'lap1',
    tanggalRequest: '2024-05-20',
    perusahaan: 'PT. Sejahtera Abadi',
    cabang: 'Jakarta Selatan',
    posisiPekerjaan: 'Account Officer',
    statusKandidat: 'Selesai',
    tanggaTerbit: '2024-05-22',
    sumberKandidat: 'Job Portal',
    namaLengkap: 'Andi Wijaya',
    jenisKelamin: 'Laki-laki',
    tempatTglLahir: 'Bekasi, 12 Juni 1996',
    nomorKTP: '3275123456780001',
    alamatDomisili: 'Jl. Mawar No. 5, Bekasi',
    alamatKTP: 'Jl. Mawar No. 5, Bekasi',
    noHpWa: '081298765432',
    agama: 'Islam',
    namaIbuKandung: 'Rina Marlina',
    tempatTglLahirIbuKandung: 'Cirebon, 1 Januari 1975',
    bidangUsaha: 'Financing',
    pengalamanPekerjaan: 'PT. Makmur Jaya - Marketing',
    masaKerjaKandidat: '2 tahun',
    referensi: 'Bapak Subagio - Manager',
    nomorTeleponReferensi: '081122334455',
    alasanResign: 'Mencari peluang karir yang lebih baik',
    akunSosialMedia: 'IG: @andiwijaya',
    email: 'andi.wijaya@example.com',
    golDarah: 'A',
    masalahKehadiran: 'Tidak ada',
    relasiDenganAtasan: 'Baik',
    terkaitIntegritas: 'Tidak ada catatan negatif',
    performance: 'Memenuhi target secara konsisten',
    penjelasanResign: 'Ingin berkembang di perusahaan yang lebih besar.',
    hasilRekomendasi: 'Direkomendasikan',
    justifikasi: 'Kandidat memiliki pengalaman yang relevan dan rekam jejak yang baik.',
    keterangan: 'Proses verifikasi berjalan lancar.',
  },
];

export const DUMMY_WOM_DATA: WomData[] = [
  {
    id: 'wom1',
    tanggalReffCheck: '2024-07-28',
    namaPelamar: 'Rina Hartati',
    cabang: 'Surabaya',
    lokasiKerja: 'Surabaya',
    bu: 'Jawa Timur',
    source: 'Walk-in',
    jenisKelamin: 'P',
    tempatLahir: 'Gresik',
    tanggalLahir: '1997-08-19',
    nomorKtp: '3578012345670003',
    agama: 'Islam',
    alamatKtp: 'Jl. Kenjeran No. 20, Surabaya',
    noTelp: '081333444555',
    namaIbuKandung: 'Sri Wahyuni',
    tempatLahirIbu: 'Lamongan',
    tanggalLahirIbu: '1975-02-15',
    statusKandidat: 'Rekomendasi',
    posisiDilamar: 'Customer Service',
    pengalaman: '2 Tahun di Bank Swasta',
    namaPerusahaan: 'Bank Sentosa',
    bidangUsaha: 'Perbankan',
    pemberiReferensi: 'Bapak Hartono',
    nomorTeleponReferensi: '081222333444',
    jabatanReferensi: 'Branch Manager',
    jabatanTerakhirKandidat: 'Senior Customer Service',
    masaKerjaKandidat: '2022-2024',
    masalahKehadiran: 'Tidak ada',
    tidakMasukTanpaIzin: 'Tidak pernah',
    masalahKesehatan: 'Tidak ada',
    relasiDengan: 'Sangat baik dengan rekan kerja dan atasan',
    terkaitIntegritas: 'Sangat jujur dan dapat dipercaya',
    performance: 'Selalu melebihi target kepuasan pelanggan',
    alasanResign: 'Ingin mencari jenjang karir yang lebih tinggi',
    penjelasanResign: 'Perusahaan sebelumnya tidak menawarkan promosi internal.',
    facebook: 'rina.hartati.real',
    instagram: 'rhartati',
    twitter: '',
    akunMediaSosialLainnya: 'LinkedIn: rina-hartati',
    kelebihanKandidat: 'Komunikatif, sabar, dan problem solver yang baik.',
    kekuranganKandidat: 'Terkadang terlalu perfeksionis.',
    email: 'rina.hartati@example.com',
    golonganDarah: 'B',
    rekomendasi: 'Sangat Direkomendasikan',
    justifikasi: 'Kandidat menunjukkan kompetensi dan etos kerja yang tinggi.'
  }
];

export const SIGNATORIES = [
  { name: 'Suci Ramanda Putri', image: suciSignature },
  { name: 'Yeni Kristanti', image: yeniSignature },
  { name: 'Wisnu Pramusinto', image: wisnuSignature },
  { name: 'Cahya Latfah Juniar', image: cahyaSignature },
  { name: 'Nur Kholifah', image: nurKholifahSignature },
  { name: 'Annisa Destiana', image: annisaSignature },
  { name: 'Febriana', image: febrianaSignature },
  { name: 'Paramita', image: paramitaSignature },
  { name: 'Bimo Tri Nugroho', image: bimoSignature },
];

export const WOM_JATENG_REKOMENDASI_BY = ['Suci Ramanda Putri', 'Cahya Latfah Juniar', 'Nur Kholifah'];
export const WOM_JATENG_DIPERIKSA_OLEH = 'Yeni Kristanti';
export const WOM_JATENG_DIKETAHUI_OLEH = 'Wisnu Pramusinto';


export const DUMMY_WOM_JATENG_REFCEK_DATA: WomJatengRefcekData[] = [
  {
    id: 'wjr1',
    createdAt: new Date().toISOString(),
    namaKandidat: 'FIRYAL SALSABILA',
    posisiDilamar: 'MAO MOTOR',
    cabangKapos: 'KAJEN',
    statusKandidat: 'New Hire Eksternal',
    pengalaman: ['Fresh graduated, pengalaman freelance'],
    namaPerusahaan: 'MEMBANTU IBU BERJUALAN KUE (AGUSTUS 2024 S.D SAAT INI)',
    pemberiReferensiNama: 'Ibu Kandidat',
    pemberiReferensiJabatan: 'Pemilik Usaha',
    pemberiReferensiTelp: '081234567890',
    masaKerjaTahun: '0',
    masaKerjaBulan: '1',
    masalahKehadiran: 'Tepat Waktu',
    tidakMasukIzin: '0',
    masalahKesehatan: 'Tidak Pernah Sakit yang Berkepanjangan',
    masalahKesehatanDetail: '',
    relasiAtasan: 'Baik',
    relasiAtasanDetail: '',
    relasiRekan: 'Baik',
    relasiRekanDetail: '',
    relasiBawahan: 'Baik',
    relasiBawahanDetail: '',
    integritas: 'Tidak ada masalah Fraud',
    integritasDetail: '',
    performance: 'On Target',
    alasanResignI: 'Mengundurkan Diri Baik-Baik',
    alasanResignII: [],
    alasanResignIII: '',
    alasanResignIVPenjelasan: 'Mencari pekerjaan tetap.',
    akunMedsosAlamat: 'CACAAFIR',
    akunMedsosStatus: ['Baik - Akun tidak mengandung hal negatif'],
    akunMedsosLainnya: '',
    rekomendasi: 'Direkomendasikan',
    justifikasi: 'Kandidat menunjukkan motivasi yang tinggi untuk belajar dan berkembang.',
    email: 'salsabilafir3@gmail.com',
    direkomendasikanOleh: 'Suci Ramanda Putri',
    diperiksaOleh: 'Yeni Kristanti',
    diketahuiOleh: 'Wisnu Pramusinto',
  }
];

export const WOM_SULAWESI_REKOMENDASI_BY = ['Cahya Latfah Juniar', 'Nur Kholifah', 'Suci Ramanda Putri'];
export const WOM_SULAWESI_DIPERIKSA_OLEH = 'Yeni Kristanti';
export const WOM_SULAWESI_DIKETAHUI_OLEH = 'Wisnu Pramusinto';

export const DUMMY_WOM_SULAWESI_REFCEK_DATA: WomSulawesiRefcekData[] = [
    {
        id: 'wsr1',
        createdAt: new Date().toISOString(),
        namaKandidat: 'Andi Mappasessu',
        posisiDilamar: 'Field Collector',
        cabangKapos: 'Makassar',
        statusKandidat: 'New Hire Eksternal',
        pengalaman: 'Pengalaman Kerja',
        namaPerusahaan: 'PT. Angin Ribut Finance',
        pemberiReferensiNama: 'Daeng Situju',
        pemberiReferensiJabatan: 'Collection Head',
        pemberiReferensiTelp: '081122334455',
        masaKerjaTahun: '2',
        masaKerjaBulan: '3',
        masalahKehadiran: 'Tepat Waktu',
        tidakMasukIzin: '0',
        masalahKesehatan: 'Tidak Pernah Sakit yang Berkepanjangan',
        masalahKesehatanDetail: '',
        relasiAtasan: 'Baik',
        relasiAtasanDetail: '',
        relasiRekan: 'Baik',
        relasiRekanDetail: '',
        relasiBawahan: 'Baik',
        relasiBawahanDetail: '',
        integritas: 'Tidak ada masalah Fraud',
        integritasDetail: '',
        performance: 'Exceed Target',
        alasanResignI: 'Mengundurkan Diri Baik-Baik',
        alasanResignII: ['Tidak Perpanjang Kontrak'],
        alasanResignIII: '',
        alasanResignIVPenjelasan: 'Mencari kompensasi yang lebih baik.',
        akunMedsosAlamat: 'andi.mappa',
        akunMedsosStatus: ['Baik - Akun tidak mengandung hal negatif'],
        akunMedsosLainnya: '',
        kelebihanKandidat: 'Negosiasi kuat, persisten, dan paham area lokal.',
        kekuranganKandidat: 'Kurang teliti dalam administrasi.',
        rekomendasi: 'Direkomendasikan',
        justifikasi: 'Kandidat memiliki potensi besar untuk mencapai target di cabang Makassar.',
        email: 'andi.mappa@example.com',
        direkomendasikanOleh: WOM_SULAWESI_REKOMENDASI_BY[2],
        diperiksaOleh: WOM_SULAWESI_DIPERIKSA_OLEH,
        diketahuiOleh: WOM_SULAWESI_DIKETAHUI_OLEH,
    }
];

export const MAF_REKOMENDASI_BY = ['Cahya Latfah Juniar', 'Nur Kholifah', 'Suci Ramanda Putri'];
export const MAF_DIPERIKSA_OLEH = 'Yeni Kristanti';
export const MAF_DIKETAHUI_OLEH = 'Bimo Tri Nugroho';

export const DUMMY_MAF_REFCEK_DATA: MafRefcekData[] = [
    {
        id: 'maf1',
        createdAt: new Date().toISOString(),
        namaKandidat: 'SIMON BERLIN PANGARIBUAN. SE',
        posisiDilamar: 'COLLECTION',
        cabangKapos: 'MEDAN',
        statusKandidat: 'New Hire Eksternal',
        pengalaman: 'Pengalaman Kerja',
        namaPerusahaan: 'KSP SAHABAT MITRA SEJATI ( OS PT VALDO SUMBER DAYA MANDIRI )',
        pemberiReferensiDivisi: 'COLLECTION',
        pemberiReferensiNama: 'BPK DIDING SUNARDI',
        pemberiReferensiJabatan: 'BRANCH MANAGER CAB MEDAN',
        pemberiReferensiTelp: '081260605113',
        masaKerjaTahun: '8',
        masaKerjaBulan: '2',
        masalahKehadiran: 'Tepat Waktu',
        tidakMasukIzin: '0',
        masalahKesehatan: 'Tidak Pernah Sakit yang Berkepanjangan',
        masalahKesehatanDetail: '',
        relasiAtasan: 'Baik',
        relasiAtasanDetail: '',
        relasiRekan: 'Baik',
        relasiRekanDetail: '',
        relasiBawahan: 'Baik',
        relasiBawahanDetail: '',
        integritas: 'Tidak ada masalah Fraud',
        integritasDetail: '',
        performance: 'On Target',
        alasanResignI: 'Mengundurkan Diri Baik-Baik',
        alasanResignII: ['Tidak Perpanjang Kontrak'],
        alasanResignIII: '',
        alasanResignIVPenjelasan: 'HABIS KONTRAK',
        akunMedsosAlamat1: 'SIMON PANGARIBUAN',
        akunMedsosAlamat2: 'SIMON_BERLIN_PANGARIBUAN',
        akunMedsosStatus: 'Baik - Akun tidak mengandung hal negatif',
        akunMedsosLainnya: '',
        jenisAngsuran: ['Motor', 'Mobil'],
        tenorCicilan: '24',
        tunggakan: 'Tidak',
        kartuKredit: 'Tidak',
        rekomendasi: 'Direkomendasikan',
        justifikasi: '',
        email: 'simonpangaribuan93@gmail.com',
        direkomendasikanOleh: MAF_REKOMENDASI_BY[2],
        diperiksaOleh: MAF_DIPERIKSA_OLEH,
        diketahuiOleh: MAF_DIKETAHUI_OLEH,
    }
];

export const MCF_REKOMENDASI_BY = ['Cahya Latfah Juniar', 'Nur Kholifah', 'Suci Ramanda Putri'];
export const MCF_DIPERIKSA_OLEH = 'Yeni Kristanti';
export const MCF_DIKETAHUI_OLEH = 'Bimo Tri Nugroho';

export const DUMMY_MCF_REFCEK_DATA: McfRefcekData[] = [
    {
        id: 'mcf1',
        createdAt: new Date().toISOString(),
        namaKandidat: 'JANE DOE',
        posisiDilamar: 'CREDIT ANALYST',
        cabangKapos: 'JAKARTA PUSAT',
        statusKandidat: 'New Hire Eksternal',
        pengalaman: ['Pengalaman Kerja'],
        namaPerusahaan: 'PT. FINANSIAL SEJAHTERA',
        pemberiReferensiNama: 'JOHN SMITH',
        pemberiReferensiJabatan: 'HEAD OF CREDIT',
        pemberiReferensiTelp: '081298765432',
        masaKerjaTahun: '3',
        masaKerjaBulan: '6',
        masalahKehadiran: 'Tepat Waktu',
        tidakMasukIzin: '0',
        masalahKesehatan: 'Tidak Pernah Sakit yang Berkepanjangan',
        masalahKesehatanDetail: '',
        relasiAtasan: 'Baik',
        relasiAtasanDetail: '',
        relasiRekan: 'Baik',
        relasiRekanDetail: '',
        relasiBawahan: 'Baik',
        relasiBawahanDetail: '',
        integritas: 'Tidak ada masalah Fraud',
        integritasDetail: '',
        performance: 'Exceed Target',
        alasanResignI: 'Mengundurkan Diri Baik-Baik',
        alasanResignII: ['PHK', 'Reorganisasi'],
        alasanResignIII: '',
        alasanResignIVPenjelasan: 'Perusahaan melakukan restrukturisasi organisasi.',
        akunMedsosAlamat: 'IG: @janedoe.official',
        akunMedsosStatus: ['Baik - Akun tidak mengandung hal negatif'],
        akunMedsosLainnya: '',
        jenisAngsuran: ['Mobil', 'KPR'],
        tenorCicilan: '36',
        tunggakan: 'Tidak',
        kartuKredit: 'Iya',
        rekomendasi: 'Direkomendasikan',
        justifikasi: 'Kandidat memiliki pengalaman yang sangat relevan dan performa yang terbukti.',
        email: 'jane.doe@example.com',
        dibuatOleh: MCF_REKOMENDASI_BY[0],
        diperiksaOleh: MCF_DIPERIKSA_OLEH,
        diketahuiOleh: MCF_DIKETAHUI_OLEH,
    }
];

export const ADIRA_REKOMENDASI_BY = ['Cahya Latfah Juniar', 'Nur Kholifah', 'Suci Ramanda Putri'];
export const ADIRA_DIPERIKSA_OLEH = 'Yeni Kristanti';
export const ADIRA_DIKETAHUI_OLEH = 'Wisnu Pramusinto';

export const DUMMY_ADIRA_REFCEK_DATA: AdiraRefcekData[] = [
    {
        id: 'adira1',
        createdAt: new Date().toISOString(),
        namaKandidat: 'BAMBANG PAMUNGKAS',
        posisiDilamar: 'BRANCH MANAGER',
        cabangKapos: 'SURABAYA',
        statusKandidat: 'New Hire Eksternal',
        pengalaman: ['Pengalaman Kerja'],
        namaPerusahaan: 'PT. LINTAS SAMUDERA',
        pemberiReferensiNama: 'SRI MULYANI',
        pemberiReferensiJabatan: 'HR DIRECTOR',
        pemberiReferensiTelp: '085612345678',
        masaKerjaTahun: '5',
        masaKerjaBulan: '0',
        masalahKehadiran: 'Tepat Waktu',
        tidakMasukIzin: '0',
        masalahKesehatan: 'Tidak Pernah Sakit yang Berkepanjangan',
        masalahKesehatanDetail: '',
        relasiAtasan: 'Baik',
        relasiAtasanDetail: '',
        relasiRekan: 'Baik',
        relasiRekanDetail: '',
        relasiBawahan: 'Baik',
        relasiBawahanDetail: '',
        integritas: 'Tidak ada masalah Fraud',
        integritasDetail: '',
        performance: 'Exceed Target',
        alasanResignI: 'Mengundurkan Diri Baik-Baik',
        alasanResignII: ['Reorganisasi'],
        alasanResignIII: '',
        alasanResignIVPenjelasan: 'Ingin mencari tantangan baru di industri multifinance.',
        akunMedsosAlamat: 'LinkedIn: bambang-pamungkas',
        akunMedsosStatus: ['Baik - Akun tidak mengandung hal negatif'],
        akunMedsosLainnya: '',
        jenisAngsuran: ['Mobil', 'KPR'],
        tenorCicilan: '60',
        tunggakan: 'Tidak',
        kartuKredit: 'Iya',
        rekomendasi: 'Direkomendasikan',
        justifikasi: 'Pengalaman manajerial yang kuat dan rekam jejak yang terbukti.',
        email: 'bambang.p@example.com',
        dibuatOleh: ADIRA_REKOMENDASI_BY[2],
        diperiksaOleh: ADIRA_DIPERIKSA_OLEH,
        diketahuiOleh: ADIRA_DIKETAHUI_OLEH,
    }
];
